import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import type { Database } from "../src/platform/database.js";
import { seedTheBank } from "./helpers/question-bank.js";
import {
  createTestDatabase,
  makeShadowDatabase,
  testDatabaseUrl,
} from "./helpers/test-database.js";

const backendDir = fileURLToPath(new URL("..", import.meta.url));
const aQuestionId = "a0000000-0000-4000-8000-000000000001";

/**
 * The column keyword search reads, and the thing about it that is easy to lose: it is
 * written by hand in a migration, so the next `prisma migrate dev` has to leave it alone.
 */
describe("the search column", () => {
  let database: Database;

  beforeAll(async () => {
    database = createTestDatabase();
    await seedTheBank(database);
  });
  afterAll(async () => {
    await database.$disconnect();
  });

  /** Read as text, because an Unsupported column cannot be selected any other way. */
  async function vectorOf(id: string): Promise<string> {
    const [row] = await database.$queryRaw<{ vector: string }[]>`
      SELECT "searchVector"::text AS vector FROM questions WHERE id = ${id}::uuid
    `;
    return row?.vector ?? "";
  }

  it("holds the lexemes of the Question text", async () => {
    const vector = await vectorOf(aQuestionId);

    // Stemmed and lower-cased by the 'english' configuration, so "Explain" is stored
    // as "explain" and the position it was found at comes with it.
    expect(vector).toContain("'explain'");
    expect(vector).toContain("'typescript'");
  });

  it("holds the lexemes of the Answer Notes as well as the text", async () => {
    const vector = await vectorOf(aQuestionId);

    // "merging" appears only in the Answer Notes of this seeded Question.
    expect(vector).toContain("'merg'");
  });

  it("follows an edit to either field without anyone writing the column", async () => {
    await database.question.update({
      where: { id: aQuestionId },
      data: { text: "Rewritten about hydration.", answerNotes: "Rewritten about caching." },
    });

    const vector = await vectorOf(aQuestionId);

    expect(vector).toContain("'hydrat'");
    expect(vector).toContain("'cach'");
    expect(vector).not.toContain("'typescript'");
  });

  it("is indexed with GIN, which is what keeps a search off a sequential scan", async () => {
    const indexes = await database.$queryRaw<{ indexdef: string }[]>`
      SELECT indexdef FROM pg_indexes
       WHERE tablename = 'questions' AND indexname = 'questions_searchVector_idx'
    `;

    expect(indexes).toHaveLength(1);
    expect(indexes[0]!.indexdef).toContain("USING gin");
  });

  it("is generated by the database rather than written by the application", async () => {
    const [column] = await database.$queryRaw<{ generated: string }[]>`
      SELECT is_generated AS generated FROM information_schema.columns
       WHERE table_name = 'questions' AND column_name = 'searchVector'
    `;

    // ALWAYS, not NEVER: a default would be worked out once at insert and then go stale.
    expect(column?.generated).toBe("ALWAYS");
  });

  it("survives the next `prisma migrate dev`", async () => {
    const shadowUrl = await makeShadowDatabase(database);

    // What `migrate dev` does before it writes a migration: replay the history into a
    // scratch database, read it back, and compare it to the schema. Exit code 2 is a
    // difference, which is the migration that would drop the column or the index.
    const diff = execFileSync(
      `${backendDir}node_modules/.bin/prisma`,
      [
        "migrate",
        "diff",
        "--from-migrations",
        "prisma/migrations",
        "--to-schema",
        "prisma/schema.prisma",
        "--exit-code",
      ],
      {
        cwd: backendDir,
        env: {
          ...process.env,
          DATABASE_URL: testDatabaseUrl(),
          SHADOW_DATABASE_URL: shadowUrl,
        },
        encoding: "utf8",
      },
    );

    expect(diff).toContain("No difference detected");
  });
});
